"""Per-chapter art direction for the quest book (read by build.py, drawn by artlib.py).

Chapters without an entry keep the classic look. Every texture is "namespace:path" under
assets/<ns>/textures/ of an installed jar; build.py --check validates them.

Pilot chapters (stone_age, create, space): palettes, banners and shapes were designed by three
art-direction agents and harmonised by a critic (gates gear, optional diamond, milestones
pentagon -> hexagon -> octagon). Round 2 (2026-10-05, after the in-game check "very empty"):
each chapter gets a big map-space "scene" illustration (layers placed by canvas fractions,
edges dissolved into the background) so the quests sit on a picture instead of floating in a
void; the screen-space background was made finer and darker (tile_size = GUI px per block;
players here use GUI scale 4, so 12 GUI px = 48 screen px per block).
"""

STYLES = {
    # Warm firelight on cold rock. A dark basalt wall lit by an ember-orange glow, with faint glowing
    # flecks. Low campfire flames run along a granite title tablet that sits in front of cold blue-
    # grey ridges. Ochre hand stencils and a flint arrowhead mark the hunting and knapping corners,
    # and hearth and kiln glows sit behind the fire and clay sections.
    "stone_age": {'palette': {'panel_fill': [46, 32, 28],
                 'accent': [220, 150, 100],
                 'glow': [255, 124, 48],
                 'text_key_hex': '#F4A877'},
     'background': {'tiles': [{'asset': 'tfc:block/rock/raw/basalt', 'weight': 6},
                              {'asset': 'tfc:block/rock/cobble/basalt', 'weight': 3}],
                    'target_brightness': 0.1,
                    'saturation': 0.55,
                    'tint': [255, 214, 186],
                    'overlay': {'type': 'speckle', 'density': 0.15, 'color': [255, 150, 70]},
                    'tile_size': 12},
     'banner': {'ribbon_asset': 'tfc:block/rock/raw/granite',
                'icons_left': ['minecraft:item/flint', 'tfc:item/stone/knife', 'tfc:item/stone/axe'],
                'icons_right': ['tfc:item/firestarter', 'tfc:item/straw', 'tfc:item/ceramic/vessel'],
                'motif': 'flames',
                'motif_color': [255, 124, 48]},
     'decor': [],
     'shapes': {'normal': 'circle', 'milestone': 'pentagon', 'optional': 'diamond', 'gate': 'gear'},
     'scene': {'layers': [{'motif': 'sky_band',
                           'x': 0.5,
                           'y': 0.2,
                           'w': 70,
                           'h': 14,
                           'color': [150, 70, 40],
                           'alpha': 0.4},
                          {'motif': 'moon',
                           'x': 0.3,
                           'y': 0.19,
                           'w': 3.4,
                           'color': [188, 196, 214],
                           'alpha': 0.6},
                          {'motif': 'mountain_range',
                           'x': 0.5,
                           'y': 0.23,
                           'w': 72,
                           'h': 11,
                           'color': [36, 40, 52],
                           'alpha': 0.85},
                          {'motif': 'mountain_range',
                           'x': 0.45,
                           'y': 0.27,
                           'w': 66,
                           'h': 8,
                           'color': [24, 22, 26],
                           'alpha': 0.85},
                          {'motif': 'soft_glow',
                           'x': 0.5,
                           'y': 0.55,
                           'w': 50,
                           'h': 36,
                           'color': [255, 120, 45],
                           'alpha': 0.3},
                          {'motif': 'soft_glow',
                           'x': 0.6,
                           'y': 0.4,
                           'w': 16,
                           'h': 13,
                           'color': [255, 105, 35],
                           'alpha': 0.3},
                          {'motif': 'strata_band',
                           'x': 0.5,
                           'y': 0.86,
                           'w': 70,
                           'h': 9,
                           'color': [110, 80, 60],
                           'alpha': 0.35},
                          {'motif': 'cave_painting',
                           'x': 0.21,
                           'y': 0.52,
                           'w': 16,
                           'h': 13,
                           'color': [176, 84, 44],
                           'alpha': 0.72},
                          {'motif': 'cave_painting_herd',
                           'x': 0.77,
                           'y': 0.6,
                           'w': 15,
                           'h': 10,
                           'color': [176, 84, 44],
                           'alpha': 0.62},
                          {'motif': 'hand_print',
                           'x': 0.74,
                           'y': 0.38,
                           'w': 4.6,
                           'color': [176, 84, 44],
                           'alpha': 0.51,
                           'rot': 12},
                          {'motif': 'hand_print',
                           'x': 0.8,
                           'y': 0.34,
                           'w': 4,
                           'color': [176, 84, 44],
                           'alpha': 0.43,
                           'rot': -16},
                          {'motif': 'hand_print',
                           'x': 0.77,
                           'y': 0.43,
                           'w': 3.4,
                           'color': [212, 194, 162],
                           'alpha': 0.27,
                           'rot': 24},
                          {'motif': 'campfire',
                           'x': 0.5,
                           'y': 0.76,
                           'w': 6,
                           'h': 6,
                           'color': [255, 120, 40],
                           'alpha': 0.95},
                          {'motif': 'embers',
                           'x': 0.5,
                           'y': 0.7,
                           'w': 6,
                           'h': 5,
                           'color': [255, 140, 60],
                           'alpha': 0.8},
                          {'motif': 'arrowhead',
                           'x': 0.7,
                           'y': 0.8,
                           'w': 5,
                           'color': [92, 84, 82],
                           'alpha': 0.8,
                           'rot': -60},
                          {'motif': 'arrowhead',
                           'x': 0.27,
                           'y': 0.78,
                           'w': 3.6,
                           'color': [86, 80, 80],
                           'alpha': 0.75,
                           'rot': -25}]}},
    # A dim graphite workshop wall of darkened industrial-iron plates and andesite casings, with the
    # odd brass-framed plate. Faint brass ghost gears turn behind everything, and a warm lamp glow
    # sits over the middle of the bench. Cool metal with warm brass highlights; mechanical, never
    # busy. It fits 齿轮一转，文明提速 ("one turn of the gear speeds up civilization").
    "create": {'palette': {'panel_fill': [34, 33, 30],
                 'accent': [232, 184, 86],
                 'glow': [255, 190, 90],
                 'text_key_hex': '#F2C46B'},
     'background': {'tiles': [{'asset': 'create:block/industrial_iron_block', 'weight': 7},
                              {'asset': 'create:block/andesite_casing', 'weight': 1}],
                    'target_brightness': 0.1,
                    'saturation': 0.6,
                    'tint': [232, 236, 244],
                    'overlay': {'type': 'gear_ghosts', 'density': 0.3, 'color': [214, 164, 80]},
                    'tile_size': 12,
                    'contrast_sd': 0.008},
     'banner': {'ribbon_asset': 'tfc:block/metal/smooth/brass',
                'icons_left': ['create:item/andesite_alloy', 'create:item/goggles', 'create:item/whisk'],
                'icons_right': ['create:item/brass_hand',
                                'tfc:item/metal/ingot/brass',
                                'create:item/precision_mechanism'],
                'motif': 'cogs',
                'motif_color': [214, 164, 80]},
     'decor': [],
     'shapes': {'normal': 'rsquare', 'milestone': 'hexagon', 'optional': 'diamond', 'gate': 'gear'},
     'scene': {'layers': [{'motif': 'shaft',
                           'x': 0.5,
                           'y': 0.19,
                           'w': 58,
                           'h': 1.0,
                           'color': [112, 106, 98],
                           'alpha': 0.55},
                          {'motif': 'blueprint',
                           'x': 0.5,
                           'y': 0.5,
                           'w': 64,
                           'h': 48,
                           'color': [110, 160, 215],
                           'alpha': 0.18},
                          {'motif': 'soft_glow',
                           'x': 0.5,
                           'y': 0.5,
                           'w': 50,
                           'h': 34,
                           'color': [255, 186, 90],
                           'alpha': 0.22},
                          {'motif': 'shaft',
                           'x': 0.8,
                           'y': 0.33,
                           'w': 14,
                           'h': 1.0,
                           'color': [112, 106, 98],
                           'alpha': 0.6,
                           'rot': 90},
                          {'motif': 'windmill_sails',
                           'x': 0.8,
                           'y': 0.19,
                           'w': 13,
                           'color': [150, 110, 70],
                           'alpha': 0.95,
                           'rot': 20},
                          {'motif': 'cog', 'x': 0.88, 'y': 0.55, 'w': 20, 'color': [92, 68, 46], 'alpha': 0.9},
                          {'motif': 'cog', 'x': 0.73, 'y': 0.42, 'w': 6, 'color': [132, 95, 46], 'alpha': 0.8},
                          {'motif': 'shaft',
                           'x': 0.25,
                           'y': 0.34,
                           'w': 9,
                           'h': 1.0,
                           'color': [112, 106, 98],
                           'alpha': 0.6},
                          {'motif': 'cog', 'x': 0.12, 'y': 0.34, 'w': 15, 'color': [86, 63, 43], 'alpha': 0.88},
                          {'motif': 'cog', 'x': 0.31, 'y': 0.34, 'w': 3.5, 'color': [132, 95, 46], 'alpha': 0.8},
                          {'motif': 'water_wheel',
                           'x': 0.2,
                           'y': 0.7,
                           'w': 14,
                           'color': [110, 80, 52],
                           'alpha': 0.95},
                          {'motif': 'belt',
                           'x': 0.5,
                           'y': 0.74,
                           'w': 26,
                           'h': 3.0,
                           'color': [118, 114, 106],
                           'alpha': 0.6},
                          {'motif': 'gear_cluster',
                           'x': 0.74,
                           'y': 0.8,
                           'w': 10,
                           'color': [132, 95, 46],
                           'alpha': 0.8}]}},
    # A violet void with quiet starlight, like the view from a porthole. Lunar deepslate fades into a
    # cold violet night full of tiny stars. A ringed Glacio-like planet, a dim red Mars and a small
    # grey Moon hang at the edges of the route. Lonely, cold and grand: the last chapter of the book.
    "space": {'palette': {'panel_fill': [16, 14, 38],
                 'accent': [176, 150, 255],
                 'glow': [118, 88, 222],
                 'text_key_hex': '#BFAEFF'},
     'background': {'tiles': [{'asset': 'ad_astra:block/moon_deepslate', 'weight': 6},
                              {'asset': 'ad_astra:block/moon_stone', 'weight': 2},
                              {'asset': 'ad_astra:block/glacio_stone', 'weight': 1}],
                    'target_brightness': 0.09,
                    'saturation': 0.5,
                    'tint': [196, 178, 255],
                    'overlay': {'type': 'starfield', 'density': 0.3, 'color': [215, 205, 255]},
                    'tile_size': 12},
     'banner': {'ribbon_asset': 'ad_astra:block/glacio_stone',
                'icons_left': ['ad_astra:item/space_helmet',
                               'ad_astra:item/rocket_nose_cone',
                               'ad_astra:item/steel_engine'],
                'icons_right': ['ad_astra:item/oxygen_gear',
                                'ad_astra:item/rocket_fin',
                                'ad_astra:item/astrodux'],
                'motif': 'planet_rings',
                'motif_color': [150, 125, 240]},
     'decor': [],
     'shapes': {'normal': 'circle', 'milestone': 'octagon', 'optional': 'diamond', 'gate': 'gear'},
     'scene': {'layers': [{'motif': 'nebula_glow',
                           'x': 0.25,
                           'y': 0.3,
                           'w': 34,
                           'h': 26,
                           'color': [120, 70, 215],
                           'alpha': 0.55},
                          {'motif': 'nebula_glow',
                           'x': 0.76,
                           'y': 0.66,
                           'w': 36,
                           'h': 24,
                           'color': [55, 95, 215],
                           'alpha': 0.5},
                          {'motif': 'nebula_glow',
                           'x': 0.64,
                           'y': 0.2,
                           'w': 22,
                           'h': 14,
                           'color': [205, 80, 170],
                           'alpha': 0.3},
                          {'motif': 'milky_way',
                           'x': 0.5,
                           'y': 0.45,
                           'w': 80,
                           'h': 16,
                           'color': [215, 205, 255],
                           'alpha': 0.45,
                           'rot': -22},
                          {'motif': 'planet_horizon',
                           'x': 0.5,
                           'y': 0.84,
                           'w': 74,
                           'h': 13,
                           'color': [62, 116, 206],
                           'alpha': 0.95},
                          {'motif': 'ringed_planet',
                           'x': 0.84,
                           'y': 0.22,
                           'w': 20,
                           'h': 13,
                           'color': [165, 150, 235],
                           'alpha': 0.95,
                           'rot': 14},
                          {'motif': 'moon',
                           'x': 0.16,
                           'y': 0.24,
                           'w': 6.5,
                           'color': [190, 196, 212],
                           'alpha': 0.95},
                          {'motif': 'planet',
                           'x': 0.15,
                           'y': 0.52,
                           'w': 7.5,
                           'color': [186, 96, 60],
                           'alpha': 0.95},
                          {'motif': 'star_cluster',
                           'x': 0.38,
                           'y': 0.7,
                           'w': 8,
                           'color': [225, 215, 255],
                           'alpha': 0.6},
                          {'motif': 'star_cluster',
                           'x': 0.9,
                           'y': 0.4,
                           'w': 6,
                           'color': [225, 215, 255],
                           'alpha': 0.55},
                          {'motif': 'satellite',
                           'x': 0.27,
                           'y': 0.19,
                           'w': 7,
                           'h': 3.5,
                           'color': [200, 200, 210],
                           'alpha': 0.9,
                           'rot': -8},
                          {'motif': 'comet',
                           'x': 0.55,
                           'y': 0.15,
                           'w': 13,
                           'h': 3.5,
                           'color': [200, 225, 255],
                           'alpha': 0.6,
                           'rot': 14},
                          {'motif': 'rocket',
                           'x': 0.82,
                           'y': 0.55,
                           'w': 3.6,
                           'h': 11,
                           'color': [190, 70, 60],
                           'alpha': 1.0,
                           'rot': 12}]}},
}
