from qlib import *

ch = Chapter("food", "饮水与食物", icon="tfc:ceramic/pot", group="survival", order=1,
             theme="food", subtitle="一锅开水，一块粗饼，一整个冬天的储备")

# ============================================================ 第一节 · 饮水、生火与屠宰
ch.quest("start", 0, 0, "口渴与生水", icon="tfc:ceramic/jug", shape="gear", size=1.5,
         deps=["00_welcome:first_year"],
         subtitle="河水能解渴，也能要命",
         desc=["&o&7「河水清澈见底，可底下藏着什么，谁也说不准。」&r",
               "",
               "TFC 有独立的&6口渴值&r（饥饿条旁边的水滴）。口渴或饥饿太低时你会&c变慢并持续掉血&r。",
               "",
               "&e喝水方式：&r",
               "&7- 空手（选中一个空的快捷栏格）对着水源&e右键&r直接喝",
               "&7- &6陶壶&r：对着水&e右键&r装水，&e按住右键&r喝，可随身携带",
               "",
               "&c本包的生水有风险：&r直接喝河水 / 湖水有概率获得&c疲惫、反胃、中毒&r，",
               "极小概率&c感染&r。&c海水&r只会让你更渴。",
               "{@pagebreak}",
               "&a安全的饮用水&r（没有副作用）：",
               "&7- &6开水&r、&6纯净水&r、&6草药水&r、&6矿泉水&r、&6牛奶&r",
               "",
               "本节教你用&6陶锅&r做出前三种。在那之前，紧急时喝点河水总比渴死强，",
               "但别把它当成习惯。",
               "",
               "&a小技巧：&r把营地建在&6河边或湖边&r——水、鱼、黏土、日后的水车动力都在这里。"],
         tasks=[item("tfc:ceramic/jug", title="陶壶")],
         rewards=[item("tfc:food/cooked_cod", 3), item("tfc:straw", 8), xp(30)])

ch.quest("firepit", 2, 0, "篝火烹饪", icon="tfc:firepit", deps=["start"], shape="hexagon", size=1.25,
         desc=["&6篝火&r是这一章的心脏：取暖、照明、烤肉、烧水都靠它。",
               "",
               "&e搭建：&r",
               "&e1.&r 在同一格地面上丢下 &61 根原木 + 3 根木棍&r（可再加最多 5 份&6引火物&r，每份 +10% 成功率）",
               "&e2.&r 用&6生火器&r（2 根木棍合成）对着那一格&e按住右键&r，直到冒烟起火",
               "",
               "&e使用：&r右键打开界面——上方 4 格放燃料（自动从上往下补），中间一格放要加热的东西。",
               "&7- 木棍放进去能做成 2 支火把",
               "&7- 用&6铲子&r右键可以熄火",
               "&7- &c松木和松果是劣质燃料&r，会冒黑烟",
               "{@pagebreak}",
               "&a篝火烤熟的食物保质期 +33%&r，比木炭炉、高炉烤出来的更耐放。",
               "",
               "&c常见的坑：&r",
               "&7- 熟了要及时取出——一直放着会继续升温，最后&c烧焦&r",
               "&7- 篝火靠近茅草、木头建筑时注意防火"],
         tasks=[tag("tfc:foods/cooked_meats", 4, title="任意熟肉 ×4")],
         rewards=[item("tfc:firestarter"), item("tfc:wood/log/oak", 8), xp(40)])

ch.quest("raw_food", 2, -2.5, "别吃生的", icon="tfc:food/beef", deps=["start"],
         desc=["本包加入了&6生食惩罚&r：",
               "&7- 吃&c生肉&r会有概率&c食物中毒&r、饥饿",
               "&7- 吃没煮过的生食材还可能带来&c虚弱、挖掘疲劳、缓慢&r等减益",
               "",
               "所以：&e肉、鱼、蛋都先烤熟再吃&r。水果和一部分蔬菜可以直接吃，但烹饪后营养和保质期都更好。",
               "",
               "&a小技巧：&r把鼠标停在食物上看提示——生熟、营养、保质期一目了然。"],
         tasks=[checkmark("我会把肉烤熟再吃")],
         rewards=[item("tfc:food/cooked_salmon", 2), xp(20)])

ch.quest("butcher", 4, -2.5, "屠夫乐事", icon="butchersdelight:dead_cow", deps=["raw_food"],
         shape="hexagon", size=1.25,
         subtitle="尸体是食材，石刀就能处理",
         desc=["狩猎后拿到&6整只动物尸体&r，却没拿到足够的肉？本包的&6屠夫乐事&r让你把尸体继续分割。",
               "",
               "&a石器时代就能处理大型尸体。&r本包已有&6尸体 + 刀&r的背包合成路线，牛、猪、羊、山羊等都可用。",
               "&c不用先做挂钩，也不用等炼铁。&r下一任务会带你实际分割。",
               "",
               "&e先准备一把 TFC 石刀：&r",
               "&7- 石刀的制作见「石器时代 · 石刀」，已有的刀可直接使用",
               "&7- 本包把 TFC 石刀和金属刀都接入了分割配方",
               "&7- 尸体也会腐烂，拿到后看保质期，&6尽快处理&r",
               "",
               "&a小技巧：&r对尸体按 &eU&r 看用途，优先找「无序合成」中的刀具配方。",
               "死亡时零散掉肉与尸体分割是两回事；不要只等动物直接掉肉。"],
         tasks=[tag("tfc:knives", title="任意刀")],
         rewards=[item("tfc:food/cooked_beef", 3), xp(30)])

ch.quest("butcher_process", 6, -2.5, "背包分割", icon="tfc:stone/knife/sedimentary", deps=["butcher"],
         desc=["&6一只未腐烂的尸体 + 一把刀&r，就能把猎物变成肉和副产物。",
               "",
               "&e1.&r 打开背包，在 &62×2 合成格&r里放入&6尸体&r和&6石刀&r，位置不限",
               "&e2.&r 取出结果，刀会&6消耗耐久&r；检查背包和周围地面，把副产物一起收好",
               "&e3.&r 肉放入&6篝火&r烤熟，暂时吃不完的按本章保存任务处理",
               "",
               "&6实例：&r牛尸体可分出 &616 份生牛肉&r，并得到骨头、牛皮、膀胱、凝乳酶和油脂。",
               "鸡尸体可分出 &62 份生鸡肉&r，并得到骨头与羽毛。猪、羊、山羊等的产物见各自 JEI 用途。",
               "{@pagebreak}",
               "&c合成不出结果时：&r",
               "&7- 尸体是否已经&c腐烂&r？腐烂尸体不能用于这条配方",
               "&7- 是否放入了正确的&6尸体物品&r，而不是摆放后的尸体方块？",
               "&7- 小动物也要看具体配方；本包兔子背包配方明确使用&6棕色兔尸体&r，别把所有颜色都当成通用材料",
               "",
               "&6兽皮也要继续处理：&r牛皮等模组兽皮还需要转成 TFC 生兽皮，才能接上茅草床与制革路线。",
               "具体刮制操作见「石器时代 · 兽皮刮制」；完整制革见「铜器时代 · 制革与风箱」。",
               "",
               "&a完成方式：&r亲手用一只尸体和刀分割，收好肉与副产物后勾选。本任务不要求先获得金属工具。"],
         tasks=[checkmark("我用尸体和刀在背包里完成过分割")],
         rewards=[item("tfc:wood/log/oak", 8), xp(35)])

ch.quest("butcher_hook", 4, 2.5, "挂钩分割", icon="butchersdelight:hook", deps=["butcher_process"],
         optional=True, shape="diamond", hide_lines=True,
         subtitle="铜器时代后的可选屠宰方式",
         desc=["想把大型尸体挂起来，逐步剥皮、切块，可以在铜器时代添置&6屠宰挂钩&r。",
               "",
               "&6本包配方：&r在&6铜砧或更高级的砧&r上把&6铜棒&r锻成挂钩；铜棒也可由铜锭在铜砧上锻出。",
               "&e按 R 看挂钩的砧配方&r，选择计划后按要求完成冲压、击打和弯曲。可用其他金属棒见 JEI。",
               "",
               "&c挂钩不是开局取肉的前置。&r还没有砧时，继续用上一任务的&6尸体 + 石刀&r合成即可。",
               "{@pagebreak}",
               "&e悬挂分割：&r",
               "&e1.&r 把挂钩放在&6支撑方块下方&r，预留站位和处理尸体的空间",
               "&e2.&r 手持&6大型动物尸体&r，对挂钩&e右键&r挂上",
               "&e3.&r 换到&6TFC 刀&r，对悬挂的尸体&e逐步右键&r剥皮、分割，收好掉落物",
               "",
               "具体副产物与后续肉块加工，对得到的物品按 &eU&r 查看本包配方。"],
         tasks=[item("butchersdelight:hook", title="屠宰挂钩（铜器时代可做）")],
         rewards=[item("tfc:straw", 8), xp(35)])
ch.quest("pot", 4, 0, "陶锅", icon="tfc:ceramic/pot", deps=["firepit"], shape="hexagon", size=1.25,
         desc=["&6陶锅&r让篝火从「烤」升级到「煮」：烧水、煮汤、转化液体全靠它。",
               "",
               "&e制作：&r黏土塑形出&6未烧制的陶锅&r，坑窑烧制后得到陶锅。",
               "",
               "&e使用：&r",
               "&e1.&r 手持陶锅&e右键篝火&r，陶锅会架到篝火上（之后篝火界面会变成陶锅界面）",
               "&e2.&r 界面有 &64 格燃料&r、&65 格材料&r，最多装 &61000mB 液体&r",
               "&e3.&r 用装水的桶 / 陶壶右键陶锅倒水，放入材料，烧到足够温度后自动完成",
               "",
               "&c常见的坑：&r做好的汤要用&6碗&r右键取出；液体产物用桶或陶壶取出。"],
         tasks=[item("tfc:ceramic/pot", title="陶锅")],
         rewards=[item("tfc:ceramic/bowl", 4), item("tfc:wooden_bucket"), xp(40)])

ch.quest("boiled_water", 6, 0, "开水", icon="tfc:rock/loose/granite", deps=["pot"],
         desc=["最基础的安全饮用水。",
               "",
               "&e做法：&r陶锅里倒入 &61000mB 淡水&r，放入 &62 块松散岩石&r（任意石头），烧到 &6600°C&r 左右，",
               "持续一段时间后得到 &61000mB 开水&r（岩石会变成碎石）。",
               "",
               "&a副产品——盐：&r改用&6海水&r煮，会得到开水 + &62 份盐&r，只是耗时更长。",
               "",
               "&a小技巧：&r煮好后用&6陶壶&r或木桶装走，陶壶喝一口就是一口安全的水。"],
         tasks=[checkmark("我煮出了开水并装进了陶壶")],
         rewards=[item("tfc:rock/loose/granite", 8), xp(40)])

ch.quest("purified_water", 8, 0, "纯净水", icon="tfc:powder/charcoal", deps=["boiled_water"],
         desc=["&6纯净水&r比开水更进一步：喝下有概率获得&a速度&r或&a力量&r。",
               "",
               "&e做法：&r陶锅里倒入淡水，放入 &6木炭粉&r，加热一段时间。",
               "&7- 木炭粉：把&6木炭&r放进&6手推磨&r磨碎（手推磨见第二节）",
               "&7- 拥有 Firmalife 的&6大缸（Vat）&r后也可以在大缸里做",
               "",
               "&a小技巧：&r木炭坑一次能烧出很多木炭，留一部分磨粉专门做水。"],
         tasks=[item("tfc:powder/charcoal", 4, title="木炭粉 ×4")],
         rewards=[item("minecraft:charcoal", 8), xp(40)])

ch.quest("herbal_water", 8, -2.5, "草药水", icon="tfc:plant/bluegrass", deps=["boiled_water"],
         optional=True, shape="diamond",
         desc=["&6草药水&r：喝下有较高概率获得&a速度&r。",
               "",
               "&e做法：&r陶锅里倒入淡水，放入 &64 份草药类草&r（早熟禾、雀麦、喷泉草、果园草、黑麦草等，",
               "物品提示里能看到），慢火煮很久，剩下的草渣会变成&6煮过的草&r。",
               "",
               "&a适合：&r长途赶路前装一壶。"],
         tasks=[checkmark("我煮过一锅草药水")],
         rewards=[item("tfc:food/cooked_cod", 2), xp(30)])

ch.quest("salt", 8, 2.5, "盐", icon="tfc:powder/salt", deps=["boiled_water"],
         desc=["&6盐&r是保存肉类的关键（第四节），也是很多配方的原料。",
               "",
               "&e获取方式：&r",
               "&7- 陶锅煮&6海水&r：开水 + 2 份盐（见上一任务）",
               "&7- 把&6岩盐矿（Halite）&r放进手推磨磨碎",
               "",
               "&a小技巧：&r住在海边就多煮几锅海水，一边得开水一边攒盐。"],
         tasks=[item("tfc:powder/salt", 8, title="盐 ×8")],
         rewards=[item("tfc:ceramic/vessel", 1), xp(40)])

ch.quest("flask", 2, 2.5, "皮革水壶", icon="waterflasks:leather_flask", deps=["start"],
         optional=True, shape="diamond",
         desc=["陶壶装得少还易碎，长途探险换&6皮革水壶&r（Water Flasks）。",
               "",
               "&e材料：&r",
               "&7- &6皮革侧片&r：皮革加工，按 R 查看；皮革制作见「铜器时代 · 制革与风箱」",
               "&7- &6膀胱&r：牛、羊等尸体分割的副产物，见本节「背包分割」",
               "&7- 线 ×2 + 背包里有&6刀&r（合成时消耗耐久）",
               "",
               "水壶坏了用膀胱合成修复。后期还有&6铁水壶&r、&6红钢水壶&r，容量更大。",
               "&c注意：&r从河里直接灌的是&c生水&r，喝之前想想上面那几种安全的水。"],
         tasks=[item("waterflasks:leather_flask", title="皮革水壶")],
         rewards=[item("tfc:food/cooked_beef", 2), xp(30)])
# ============================================================ 第二节 · 谷物与面包
ch.quest("grain", 0, 7, "谷物", icon="tfc:food/barley", deps=["start"],
         desc=["&6谷物&r是最稳定的碳水来源：大麦、燕麦、黑麦、小麦、玉米、水稻。",
               "",
               "&e获取：&r",
               "&e1.&r 野外采集&6野生作物&r，或自己种（见「务农」章）",
               "&e2.&r 收获得到整株作物（如&6大麦&r）",
               "&e3.&r 和&6刀&r一起合成，脱出&6谷粒&r，并附带&6稻草&r",
               "",
               "&a小技巧：&r香蒲根、芋头根也算谷物营养，沼泽边很容易找到。"],
         tasks=[tag("tfc:foods/grains", 4, title="任意谷粒 ×4")],
         rewards=[item("tfc:straw", 8), xp(30)])

ch.quest("quern", 2, 7, "手推磨", icon="tfc:quern", deps=["grain"], shape="hexagon", size=1.25,
         desc=["&6手推磨&r把谷粒磨成面粉，也能把木炭、岩盐、矿石等磨成粉。",
               "",
               "&e搭建：&r",
               "&e1.&r 合成&6手推磨底座&r（磨光石 + 岩石，配方见 JEI）并放在地上",
               "&e2.&r 把&6手磨石&r右键装到底座上",
               "&e3.&r 手持材料&e右键中间的孔&r放入，再&e右键把手&r转动",
               "&e4.&r 产物会掉在磨盘周围的地上",
               "",
               "&c常见的坑：&r手磨石有耐久，磨坏了要换新的，多备一块。",
               "&7- 1 份谷粒 = 1 份面粉"],
         tasks=[item("tfc:quern", title="手推磨"), item("tfc:handstone", title="手磨石")],
         rewards=[item("tfc:food/barley_grain", 6), xp(40)])

ch.quest("dough", 4, 7, "面团", icon="tfc:food/barley_dough", deps=["quern"],
         desc=["&e做法：&r在合成格里放 &61~8 份面粉&r + &6装水的容器&r（木桶 / 陶壶，消耗 100mB 水），",
               "每份面粉得到 &62 份面团&r。",
               "",
               "&a小技巧：&r一次放满 8 份面粉最省水。",
               "&c注意：&r已经腐烂的面粉不能用。"],
         tasks=[tag("tfc:foods/dough", 4, title="任意面团 ×4")],
         rewards=[item("tfc:food/barley_flour", 4), xp(30)])

ch.quest("flatbread", 6, 7, "粗饼", icon="firmalife:food/barley_flatbread", deps=["dough"],
         desc=["把面团放进篝火加热，得到&6粗饼&r——本包里普通面团只能烤成粗饼，营养不如真正的面包，",
               "但足够当作早期的主食。",
               "",
               "&e做法：&r面团放进篝火中间格，烤到约 200°C 就熟了，及时取出。",
               "",
               "&a小技巧：&r粗饼也能用来做三明治（第三节）。"],
         tasks=[tag("firmalife:foods/flatbreads", 4, title="任意粗饼 ×4")],
         rewards=[item("tfc:food/barley_flour", 4), xp(30)])

ch.quest("yeast_bread", 8, 9, "发酵面包", icon="tfc:food/barley_bread", deps=["flatbread"],
         optional=True, shape="diamond",
         desc=["真正的&6面包&r需要 Firmalife 的一整套流程：",
               "&e1.&r &6酵母液&r：干燥水果 + 水密封在木桶里发酵",
               "&e2.&r &6搅拌碗&r：1000mB 酵母液 + 2 面粉 + 1 甜味剂（蜂蜜、糖等） → 3 份发酵面团",
               "&e3.&r &6烤炉&r（烤炉底 + 烤炉顶 + 烟囱）烧到 200°C 以上，用&6烤炉铲&r放入面团",
               "",
               "面包用刀可以切成面包片，做三明治更划算。",
               "&a优势：&r营养和饱食度都比粗饼高。烤炉的细节见野外指南 Firmalife 章节。"],
         tasks=[tag("tfc:foods/breads", 2, title="任意面包 ×2")],
         rewards=[item("tfc:food/barley_flour", 6), xp(50)])
# ============================================================ 第三节 · 营养与餐点
ch.quest("nutrition", 11.5, 7, "五类营养", icon="tfc:food/fruit_soup", deps=["flatbread"],
         shape="hexagon", size=1.25,
         desc=["TFC 追踪&6五类营养&r：&6谷物&r、&6水果&r、&6蔬菜&r、&6蛋白质&r、&6乳制品&r。",
               "",
               "&7- 营养值按你&e最近吃的若干份食物&r计算，只吃一种东西其他四项会慢慢掉光",
               "&7- 五项越均衡、越高，&a最大生命值越高&r",
               "&7- 在物品栏右侧的&6营养标签页&r查看当前状态",
               "&7- 鼠标停在食物上可以看到它提供哪几类营养",
               "",
               "&a本包设置：&r死亡后保留 TFC 营养；重生时仍需处理生命、饱食度与口渴的死亡惩罚。",
               "&a最省事的均衡方法：&r汤、沙拉、三明治——一份餐点就能覆盖多类营养。"],
         tasks=[checkmark("我打开过营养标签页")],
         rewards=[item("tfc:food/cooked_beef", 2), item("tfc:food/barley_flour", 4), xp(40)])

ch.quest("soup", 13.5, 6, "煮汤", icon="tfc:food/vegetables_soup", deps=["nutrition"],
         desc=["&6汤&r是早期性价比最高的餐点：把多种食材的营养合进一碗。",
               "",
               "&e做法：&r",
               "&e1.&r 陶锅架在篝火上，倒入 &61000mB 水&r",
               "&e2.&r 放入 &63~5 份&r水果 / 蔬菜 / 肉 / 谷物",
               "&e3.&r 烧开煮好后，用&6碗&r右键陶锅盛出",
               "",
               "&a小技巧：&r汤的类别由主要食材决定，但营养来自所有食材。混着放最划算。"],
         tasks=[tag("tfc:soups", 2, title="任意汤 ×2")],
         rewards=[item("tfc:ceramic/bowl", 4), xp(40)])

ch.quest("salad", 13.5, 8.25, "沙拉", icon="tfc:food/vegetables_salad", deps=["nutrition"],
         desc=["不需要火的餐点。",
               "",
               "&e做法：&r手持&6碗&r&e右键空气&r打开沙拉界面，放入最多 &65 份&r可做沙拉的食材",
               "（水果、蔬菜等，物品提示可见），取出即可。",
               "",
               "&a适合：&r野外没有锅的时候，用采来的浆果和野菜凑一顿。"],
         tasks=[tag("tfc:salads", 1, title="任意沙拉")],
         rewards=[item("tfc:ceramic/bowl", 2), xp(30)])

ch.quest("sandwich", 15.5, 8.25, "三明治", icon="tfc:food/barley_bread_sandwich", deps=["salad"],
         optional=True, shape="diamond",
         desc=["&e做法：&r合成格里放 &6刀 + 2 份面包 + 3 份食材&r（蔬菜 / 熟肉 / 乳制品），得到 &62 个三明治&r。",
               "Firmalife 的面包片、粗饼也有对应配方，详见 JEI。",
               "",
               "&a优势：&r一份三明治同时有谷物和夹心的营养，适合放在背包里当干粮。"],
         tasks=[checkmark("我做过三明治")],
         rewards=[item("tfc:food/cooked_beef", 3), xp(30)])

ch.quest("variety", 15.5, 6, "百味人生", icon="lithiccoins:coin/heart/red_steel", deps=["soup"],
         shape="hexagon", size=1.25,
         desc=["本包装有 &6Spice of Life: Carrot Edition&r：&a吃过的不同食物种类越多，最大生命值越高&r。",
               "",
               "&7- 初始 &63 颗心&r",
               "&7- 累计吃过 &65 / 10 / 30 / 60 / 90 / 120 / 150&r 种不同食物，各 +1 颗心",
               "&7- 这部分进度&a死亡不会重置&r",
               "&7- 快捷栏上方会显示进度，物品提示会标出「还没吃过」的食物",
               "",
               "&a小技巧：&r不同谷物的粗饼、不同口味的汤都算不同食物。每遇到新食材，至少尝一口。"],
         tasks=[checkmark("我会尝遍每一种新食物")],
         rewards=[item("tfc:food/cooked_salmon", 2), item("tfc:food/cooked_beef", 2), xp(50)])
# ============================================================ 第四节 · 保存
ch.quest("decay", 11.5, 0, "腐烂与密封", icon="tfc:ceramic/large_vessel", deps=["salt"],
         shape="hexagon", size=1.25,
         desc=["TFC 的食物都有&c保质期&r：鼠标停在食物上能看到过期时间，过期就会&c腐烂&r，不能再用。",
               "",
               "&e最基础的保存：陶罐与大缸&r",
               "&7- &6陶罐&r 4 格，&6大缸&r 9 格",
               "&7- 在大缸界面里&e密封&r后，里面的食物获得&6「储存」&r特性，腐烂明显变慢",
               "&7- 需要拿东西时再解封，拿完记得重新密封",
               "",
               "&c常见的坑：&r",
               "&7- 箱子里放食物会&c招老鼠&r",
               "&7- 不同时间做的同种食物不能合并成一叠——这是保质期不同导致的，不是 bug",
               "&7- 越热的地方腐烂越快，地下、北方更耐放"],
         tasks=[item("tfc:ceramic/large_vessel", title="大缸")],
         rewards=[item("tfc:ceramic/vessel", 2), xp(40)])

ch.quest("salting", 13.5, 0, "盐腌", icon="tfc:powder/salt", deps=["decay"],
         desc=["&6盐腌&r是最早能用上的肉类保存法。",
               "",
               "&e做法：&r",
               "&7- 合成格里放 &6生肉 + 盐&r，得到带「盐腌」特性的生肉",
               "&7- 或者在地上放一碗盐，手持生肉对它右键",
               "",
               "&c注意：&r只有&c生肉&r能盐腌；腌过再烤，特性会保留下来。",
               "&a小技巧：&r大量狩猎后先全部盐腌、烤熟，再密封进大缸，能撑过一整个冬天。"],
         tasks=[checkmark("我腌过一批生肉")],
         rewards=[item("tfc:powder/salt", 4), xp(40)])

ch.quest("smoking", 15.5, -2, "烟熏", icon="tfc:wool_yarn", deps=["salting"],
         optional=True, shape="diamond",
         desc=["Firmalife 的&6烟熏&r：把肉或奶酪吊在篝火上方慢慢熏，比盐腌保存得更久。",
               "",
               "&c先说一个容易踩的坑：&r吊东西用的「羊毛线」只是放在世界里的&6方块&r，&c没有物品形态&r，",
               "背包和 JEI 里都找不到它。你要准备的是&6羊毛纱&r，手持右键才会拉出这根线。",
               "",
               "&e1. 做纺锤：&r",
               "&7- 黏土塑形出十字形的&6未烧制纺锤头&r，坑窑烧成&6纺锤头&r",
               "&7- &6纺锤头 + 木棍&r在背包 2×2 合成&6陶瓷纺锤&r（按 &eR&r 看配方）",
               "&7- 本包隐藏了原版 TFC 纺锤，用陶瓷纺锤；金属纺锤同样可用",
               "&e2. 备羊毛：&r&6羊的毛皮 + 刀&r可合成 &64 份羊毛&r（另得一张大型生兽皮），也可以剪羊毛",
               "&e3. 纺纱：&r&6纺锤 + 羊毛&r无序合成 &68 根羊毛纱&r，纺锤会损耗耐久",
               "{@pagebreak}",
               "&e4. 拉线：&r找两面相对的实心墙，中间留空，手持羊毛纱&e右键&r其中一面墙，",
               "线会沿水平方向拉向对面。&6羊毛纱数量不能少于跨度&r，不够就放不出来",
               "&e5. 生火：&r篝火要在线的&6正下方 6 格以内&r（本包设置），且&c只能烧原木&r——",
               "泥炭这类非原木燃料会让食物立刻变「恶心」",
               "&e6. 挂食物：&r手持肉或奶酪&e右键&r这根线挂上去，等待约 &68 个游戏小时&r",
               "",
               "&c肉类要先泡卤水！&r熏制配方只认「卤制」，普通盐腌&c不算&r：",
               "&7- &6卤水&r = 9 份海水 + 1 份醋，在大桶里混合（醋的做法见「腌渍」）",
               "&7- 每件肉用 125 mB 卤水在大桶里密封浸泡约 4 个游戏小时",
               "&7- 奶酪不需要卤制，可直接熏",
               "",
               "&a完成方式：&r凑齐 8 根羊毛纱，再亲手拉出一根线，系统检测到放置就会完成。"],
         tasks=[item("tfc:wool_yarn", 8, title="羊毛纱 ×8"),
                advancement("firmalife:story/smoker", title="拉出一根熏制用的线")],
         rewards=[item("tfc:wood/log/oak", 16), xp(40)])

ch.quest("cellar", 17.5, -2, "地窖", icon="firmalife:climate_station", deps=["smoking"],
         optional=True, shape="diamond",
         desc=["Firmalife 的&6地窖&r是终极粮仓，也是熟成奶酪的地方。",
               "",
               "&e结构要点：&r",
               "&7- 用&6密封砖&r（需要蜂蜡）和密封门围成封闭空间",
               "&7- &6气象站&r放在第一层，贴着墙",
               "&7- 内部温度&a低于 0°C 效果好，低于 -12°C 效果更好&r",
               "&7- 可放食物架、挂架；奶酪在这里熟成",
               "",
               "&a前置：&r蜂蜡来自养蜂（Firmalife 蜂箱，见「务农」章）。完整结构见野外指南。"],
         tasks=[item("firmalife:climate_station", title="气象站")],
         rewards=[item("tfc:food/cheese", 2), xp(60)])

ch.quest("pickling", 15, 2, "腌渍", icon="tfc:wood/barrel/oak", deps=["salting"],
         optional=True, shape="diamond",
         desc=["木桶里的&6腌渍&r，适合蔬菜和肉类：",
               "&e1.&r &6醋&r：水果 + 250mB 酒在木桶里制成",
               "&e2.&r &6盐水&r：1 份醋 : 9 份海水混合",
               "&e3.&r 食物先在盐水里&6浸泡&r，再密封进醋里（每件至少 125mB）",
               "",
               "&c注意：&r打开木桶后效果会消失。酒需要先酿造，详见野外指南。"],
         tasks=[checkmark("我做过一桶腌渍食物")],
         rewards=[xp(50)])

ch.quest("drying", 13, 2, "晒干", icon="firmalife:drying_mat", deps=["decay"],
         optional=True, shape="diamond",
         desc=["Firmalife 的&6干燥垫&r：放在露天，把水果、豆腐等摆上去晒。",
               "",
               "&7- 需要&6阳光&r，大约半天完成",
               "&7- &c下雨会重置进度&r",
               "&7- 干燥水果是做&6酵母液&r（发酵面包）的原料"],
         tasks=[item("firmalife:drying_mat", title="干燥垫")],
         rewards=[item("tfc:straw", 16), xp(30)])

ch.quest("grill", 11.5, -2.5, "锻铁烤架", icon="tfc:wrought_iron_grill", deps=["decay"],
         optional=True, shape="diamond",
         desc=["铁器时代之后的升级：把&6锻铁烤架&r放在篝火上。",
               "",
               "&7- 一次可加热 &65 件&r食物",
               "&7- 烤出的食物保质期 &a+66%&r（篝火直接烤是 +33%）",
               "",
               "&e制作：&r锻铁双板在铁砧上锻造，见「铁器时代」章。"],
         tasks=[item("tfc:wrought_iron_grill", title="锻铁烤架")],
         rewards=[item("tfc:food/cooked_beef", 4), xp(40)])

ch.quest("finale", 17.5, 0, "粮仓满了", icon="tfc:ceramic/pot", shape="gear", size=1.75,
         deps=["salting", "variety"],
         subtitle="冬天来了，也不怕",
         desc=["&o&7「一锅开水，一块粗饼，一缸腌肉——这就是活过第一个冬天的全部秘密。」&r",
               "",
               "你已经掌握：",
               "&7- &6安全饮水&r：开水、纯净水、草药水",
               "&7- &6烹饪&r：篝火、陶锅、汤与沙拉",
               "&7- &6屠宰&r：未腐烂尸体加石刀，背包分割取肉与兽皮",
               "&7- &6主食&r：脱粒、磨粉、面团、粗饼",
               "&7- &6营养&r：五类均衡 + 尝遍新食物涨心",
               "&7- &6保存&r：密封大缸、盐腌，以及之后的烟熏、腌渍、地窖",
               "",
               "&a下一步：&r去「务农」章自己种粮、养牲口，不再靠运气吃饭。"],
         tasks=[checkmark("我的粮仓已经准备好过冬")],
         rewards=[item("tfc:food/barley_flour", 8), item("tfc:ceramic/large_vessel", 2),
                  levels(5), xp(100)])

# ============================================================ 章节布局
ch.section("第一节 · 饮水、生火与屠宰", ["start", "firepit", "raw_food", "butcher", "butcher_process", "butcher_hook",
                                       "pot", "boiled_water", "purified_water", "herbal_water", "salt", "flask"])
ch.section("第二节 · 谷物与面包", ["grain", "quern", "dough", "flatbread", "yeast_bread"])
ch.section("第三节 · 营养与餐点", ["nutrition", "soup", "salad", "sandwich", "variety"])
ch.section("第四节 · 保存", ["decay", "salting", "smoking", "cellar", "pickling", "drying", "grill", "finale"])
