from qlib import *

ch = Chapter("stone_age", "石器时代", icon="tfc:stone/axe/sedimentary", group="ages", order=0,
             theme="stone", subtitle="以石为刃，以火为伴")

# ============================================================ A · 石与木
ch.quest("start", 0, 0, "捡起石头", icon="tfc:rock/loose/granite", shape="gear", size=1.5,
         deps=["00_welcome:welcome"],
         subtitle="一切从地上的一块石头开始",
         desc=["&o&7「人类最早的工具，就躺在脚边。」&r",
               "",
               "地面上散落着各种&6碎石&r，&e右键&r即可捡起。岩石分为四大类：",
               "&7- &6火成喷出岩&r（玄武岩、安山岩、英安岩、流纹岩）",
               "&7- &6火成侵入岩&r（花岗岩、闪长岩、辉长岩）",
               "&7- &6变质岩&r（石英岩、板岩、千枚岩、片岩、片麻岩、大理岩）",
               "&7- &6沉积岩&r（页岩、燧石岩、泥岩、砾岩、石灰岩、白云岩、白垩）",
               "",
               "不同类别做出的石器&a耐久与效率略有区别&r，但作为起步工具都够用。",
               "&a建议：&r多捡一些，后面敲工具头会消耗石头，并且有失败概率。"],
         tasks=[tag("tfc:rock_knapping", 6, title="任意碎石 ×6")],
         rewards=[item("tfc:food/barley_bread", 4), xp(20)])

ch.quest("sticks", 2, -1.5, "树枝与木棍", icon="minecraft:stick", deps=["start"],
         desc=["&6木棍&r是石器的柄，也是生火的原料。获取方式：",
               "&7- 捡起地面上散落的&6树枝&r（右键）",
               "&7- 徒手破坏&6树叶&r或&6灌木&r有几率掉落",
               "",
               "&c注意：&r没有斧头时&c无法徒手砍树&r，原木要等做出石斧再说。",
               "8 根木棍可以捆成一个&6木棍堆&r，方便携带，也是篝火的好燃料。"],
         tasks=[tag("forge:rods/wooden", 8, title="木棍 ×8")],
         rewards=[item("minecraft:stick", 8)])

ch.quest("rough_head", 2, 1.5, "敲出第一块工具头", icon="tfc:stone/hammer_head/sedimentary",
         deps=["start"], shape="hexagon", size=1.25,
         desc=["&c本整合包修改了石器塑形！&r原版 TFC 的手持石头右键塑形界面被禁用了。",
               "",
               "&6粗略塑形：&r找到一块&6硬化岩石&r方块（悬停查看，名字以「硬化」开头），"
               "&e手持碎石左键敲击&r它：",
               "&7- 90% 概率得到 &6石锤头&r，80% 概率得到 &6石铲头&r",
               "&7- 每次消耗一块石头，并有 2 秒冷却",
               "",
               "&6继续拆分：&r手持工具头再去敲硬化岩石，可以把它拆成别的工具头：",
               "&7- 石锤头 → 石锄头 + 石标枪头",
               "&7- 石铲头 → 石斧头 + 石刀刃",
               "&7- 石斧头 / 石锄头 → 石刀刃 + 石标枪头",
               "{@pagebreak}",
               "&6精确塑形：&r背包里同时有&6凿子&r和&6刮制大兽皮&r（或皮革）时，手持石头右键才会打开传统的塑形界面。"
               "这要到铜器时代之后了。",
               "",
               "&a小技巧：&r硬化岩石常出现在裸露的山体、河岸断面和地下岩层中。手持碎石悬停可看到提示（按住 Shift）。"],
         tasks=[tag("forge:head_hammer/stone", title="石锤头"),
                tag("forge:head_shovel/stone", title="石铲头")],
         rewards=[item("tfc:rock/loose/granite", 8), xp(30)])

ch.quest("split_heads", 4, 1.5, "拆分工具头", icon="tfc:stone/axe_head/sedimentary", deps=["rough_head"],
         desc=["用上一步的工具头继续敲击硬化岩石，拆分出&6斧头&r与&6刀刃&r。",
               "",
               "&e推荐路线：&r石铲头 → 石斧头 + 石刀刃。",
               "这两样是最先需要的：&6石斧&r砍树，&6石刀&r割草、剥皮、收获。",
               "",
               "&c常见的坑：&r拆分也有失败概率，产物会掉在地上，记得捡起来。"],
         tasks=[tag("forge:head_axe/stone", title="石斧头"),
                tag("forge:head_knifes/stone", title="石刀刃")],
         rewards=[item("tfc:rock/loose/basalt", 8), xp(30)])
ch.quest("fiber", 0, 3, "植物纤维", icon="tfc_stone_tools:plant_fiber", deps=["start"],
         desc=["&6植物纤维&r是石器时代最重要的材料：绑工具、编织、晒稻草都离不开它。",
               "",
               "&e获取：&r",
               "&7- &e空手右键&r草丛：85% 概率得到纤维（草丛可能被消耗）",
               "&7- &e持刀右键&r草丛：一次 2 根，效率更高（消耗耐久）",
               "&7- 2 个&6落叶&r也可合成 1 根纤维",
               "",
               "&a建议：&r一次性多采一些，后面的植物线、植物布、晒垫和衣服都要用掉大量纤维。"],
         tasks=[item("tfc_stone_tools:plant_fiber", 16, title="植物纤维 ×16")],
         rewards=[item("tfc_stone_tools:plant_fiber", 16), xp(20)])

ch.quest("string", 2, 4.25, "搓一根线", icon="tfc_stone_tools:plant_string", deps=["fiber"],
         desc=["&63 根植物纤维&r无序合成 &61 根植物线&r。",
               "",
               "植物线用来&6捆绑石刀&r，4 根植物线可织成&6绿色植物布&r（用于晒垫和植物衣物）。",
               "",
               "&c注意：&r本整合包中植物线&c不算作普通「线」&r，不能用来做弓弦或钓竿等需要结实线材的东西。"],
         tasks=[item("tfc_stone_tools:plant_string", 6, title="植物线 ×6")],
         rewards=[item("tfc_stone_tools:plant_string", 4), xp(20)])

ch.quest("knife", 6, 1.5, "石刀", icon="tfc:stone/knife/sedimentary", deps=["split_heads", "string"],
         shape="hexagon",
         desc=["石刀的配方：&6石刀刃&r + &62 根植物线&r（对角摆放，详见 JEI）。",
               "",
               "石刀用途极广：",
               "&7- 割草获得纤维和&6稻草&r",
               "&7- 收获作物、采集浆果灌木",
               "&7- 刮制兽皮、切割食物",
               "&7- 也是一件聊胜于无的武器",
               "",
               "&a小技巧：&r刀也是很多合成配方里的「工具」，合成后只消耗耐久，不会消失。"],
         tasks=[tag("tfc:knives", title="任意刀")],
         rewards=[item("tfc_stone_tools:plant_fiber", 12), xp(30)])

ch.quest("axe", 6, -0.5, "石斧", icon="tfc:stone/axe/sedimentary", deps=["split_heads"], shape="hexagon",
         desc=["&6石斧头&r + &6木棍&r 组装成石斧（部分配方还需要植物线，以 JEI 为准）。",
               "",
               "有了斧头才能&6砍树&r。砍倒树木时会掉落原木、树枝和树苗。",
               "&c小心：&r砍倒的树会整棵倒下，不要站在树下面。",
               "",
               "&a小技巧：&r石斧也是不错的近战武器，伤害比石刀高。"],
         tasks=[tag("tfc:axes", title="任意斧")],
         rewards=[item("minecraft:stick", 8), xp(30)])

ch.quest("javelin", 6, 3.5, "标枪", icon="tfc:stone/javelin/sedimentary", deps=["split_heads"],
         desc=["&6石标枪头&r 可由石锤头、石斧头或石锄头拆分得到，与木棍组装成&6石标枪&r。",
               "",
               "标枪是石器时代的&c主武器&r：&e按住右键蓄力后松开&r投掷，伤害可观，命中后可以捡回来重复使用。",
               "",
               "&c警告：&r不要用石器去招惹&c熊、狼、狮子、老虎&r等大型掠食者。标枪适合狩猎鹿、羊、猪等猎物。"],
         tasks=[tag("tfc:javelins", title="任意标枪")],
         rewards=[item("tfc:stone/javelin/sedimentary"), xp(30)])

ch.quest("more_tools", 8, 1.5, "全套石器", icon="tfc:stone/hoe/sedimentary", deps=["knife", "axe"], optional=True,
         shape="diamond",
         desc=["剩下的工具头也组装起来吧：",
               "&6石铲&r —— 挖土、沙、砾石更快，也可熄灭篝火",
               "&6石锄&r —— 开垦耕地（务农章节会讲）",
               "&6石锤&r —— 后期用来塑形金属，也是砧的必需品",
               "",
               "&7这些工具并非必需，但能大幅提升效率。"],
         tasks=[tag("tfc:shovels", title="任意锹"), tag("tfc:hoes", title="任意锄"), tag("tfc:hammers", title="任意锤")],
         rewards=[item("tfc:food/barley_bread", 4), xp(40)])
# ============================================================ B · 火与居所
ch.quest("logs", 11.5, -1, "伐木", icon="tfc:wood/log/oak", deps=["axe"],
         desc=["用斧头砍树获得&6原木&r。原木是篝火的主燃料，也是坑窑、支撑梁和工作台的原料。",
               "",
               "&e木材加工：&r",
               "&7- 原木 → &6木材&r（需要锯，铜器时代）→ 木板、箱子、木桶",
               "&7- 在石器时代，原木主要用来&6烧火&r和&6搭坑窑&r",
               "",
               "&a小技巧：&r原木可以&6潜行右键地面&r堆成原木堆，节省物品栏。",
               "&c注意：&r砍伐时注意树木倒下的方向，别被砸到；也请顺手种下树苗。"],
         tasks=[tag("minecraft:logs", 16, title="任意原木 ×16")],
         rewards=[item("tfc:firestarter"), item("tfc:wood/log/oak", 8), xp(20)])

ch.quest("support", 11.5, -3, "支撑梁：防止塌方", icon="tfc:wood/support/oak", deps=["logs"], shape="diamond",
         desc=["&c群峦里挖矿会塌方！&r开采天然岩石时，附近没有支撑的岩石可能塌落，把你砸成肉饼。",
               "",
               "&6获取支撑梁：&r放置一根原木，用斧头&e右键剥皮&r，再次&e右键&r去皮原木即可得到支撑梁"
               "（也可以在铜器时代用锯合成）。",
               "",
               "&6用法：&r",
               "&7- 放在地上会生成&6三格高的竖梁&r",
               "&7- 两根竖梁之间（距离 ≤ 5 格）放置&6横梁&r",
               "&7- 只有&e横梁&r提供支撑：以自身为中心 &69×5×9&r 范围",
               "",
               "&a进洞挖矿前请务必备好一组支撑梁！&r"],
         tasks=[tag("forge:supports", 8, title="支撑梁 ×8")],
         rewards=[item("tfc:wood/support/oak", 8), xp(30)])

ch.quest("firepit", 13.5, -1, "第一堆篝火", icon="tfc:firepit", deps=["logs"], shape="hexagon",
         size=1.25,
         desc=["&o&7「火让黑夜不再可怕。」&r",
               "",
               "&e1.&r 用 &62 根木棍&r合成&6起火器&r（本任务前置已奖励一个）",
               "&e2.&r 在同一格地面上&e丢出&r（Q 键）&61 根原木 + 3 根木棍&r，可再加最多 5 个&6引火物&r"
               "（稻草、纸、松果……每个 +10% 成功率）",
               "&e3.&r 手持起火器&e按住右键&r对准这些物品，冒烟后有几率点燃",
               "",
               "&6篝火界面：&r左侧 4 格燃料（从最下面开始烧），右侧放要加热的物品。",
               "&7- 烤肉、烤面团可以&a延长保质期&r并恢复更多饱食度",
               "&7- 放上陶锅变成&6大锅&r可煮汤，放上锻铁烤架可同时烤 5 个",
               "{@pagebreak}",
               "&c常见的坑：&r",
               "&7- 雨天或潮湿处很难点着",
               "&7- 松木、落叶杂质多、产烟大；落叶热量太低无法烹饪",
               "&7- 篝火是&c污染源&r，室内请注意通风（见生存之道章节）",
               "&7- 用铲子右键篝火可以熄灭它"],
         tasks=[item("tfc:firepit", title="篝火")],
         rewards=[item("tfc:food/barley_bread", 4), xp(40)])

ch.quest("torch", 15.5, -1, "火把", icon="tfc:torch", deps=["firepit"],
         desc=["把&6木棍&r放进点燃的篝火里加热，1 根木棍会变成 &62 支火把&r。",
               "",
               "&c注意：&r放置在世界里的火把会&c逐渐燃尽&r变成熄灭的火把。可以用起火器或另一支燃着的火把重新点燃。",
               "",
               "&a理智提示：&r长时间处于黑暗中会降低理智，基地里多插些火把吧。"],
         tasks=[item("tfc:torch", 8, title="火把 ×8")],
         rewards=[item("tfc:torch", 16), xp(20)])

ch.quest("drying", 11.5, 1.5, "晒垫", icon="firmalife:drying_mat", deps=["string"], hide_lines=True,
         desc=["&6晒垫&r用于晾晒物品。配方：&62 块绿色植物布&r（4 根植物线 = 1 块布），或 3 片果树叶。",
               "",
               "把晒垫放在地上，&e右键&r放上物品，等待一段时间就会晒好：",
               "&7- &6植物纤维 → 稻草&r（最重要）",
               "&7- 植物线 → 晒干的植物线",
               "&7- 还可以晾晒部分食物和药草",
               "",
               "&c常见的坑：&r晒垫必须在&e露天&r，否则晾晒时间翻倍；下雨时会暂停。"],
         tasks=[item("firmalife:drying_mat", 2, title="晒垫 ×2")],
         rewards=[item("firmalife:drying_mat", 2), item("tfc_stone_tools:plant_fiber", 16)])

ch.quest("straw", 13.5, 1.5, "稻草", icon="tfc:straw", deps=["drying"],
         desc=["&6稻草&r的用途：",
               "&7- 生火的引火物",
               "&7- &6坑窑&r的必需材料（每个坑窑 8 束）",
               "&7- 合成&6茅草&r方块",
               "&7- 喂养动物、垫床",
               "",
               "&e来源：&r在晒垫上晒干植物纤维，或用刀割草时直接掉落。"],
         tasks=[item("tfc:straw", 16, title="稻草 ×16")],
         rewards=[item("tfc:straw", 16), xp(20)])

ch.quest("thatch", 15.5, 1.5, "茅草", icon="tfc:thatch", deps=["straw"],
         desc=["&64 束稻草&r合成 1 块&6茅草&r。茅草是最早的建筑方块：可以穿过（像蜘蛛网一样减速），能遮风挡雨。",
               "",
               "&a小技巧：&r植物纤维块放置在世界中也会慢慢变成茅草。",
               "",
               "&c警告：&r茅草屋&c扛不住龙卷风&r！第一年内请尽快换成石头或砖房。"],
         tasks=[item("tfc:thatch", 4, title="茅草 ×4")],
         rewards=[item("tfc:thatch", 8)])
# ============================================================ C · 衣与猎
ch.quest("plant_clothes", 0, 8, "植物衣物", icon="tfc_stone_tools:plant_chestplate", deps=["string"],
         shape="hexagon",
         desc=["赤身裸体是撑不过冬天的。最早能做的衣服是用&6绿色植物布&r和&6植物线&r缝制的植物衣物。",
               "",
               "&e合成：&r各部件在工作台中用植物布 + 植物线拼出（例如上衣分两片缝合，鞋子由左右两只组成），"
               "&e按 R 在 JEI 中查看完整配方&r。",
               "",
               "植物衣物保暖性很差，但它们是&6基础衣物&r：后面可以在&6缝纫台&r上给它们加缝毛皮、羊毛等保暖材料"
               "（见「生存之道 · 气候与衣物」）。",
               "",
               "&c入冬前&r一定要准备更暖和的衣物！"],
         tasks=[item("tfc_stone_tools:plant_helmet", title="植物帽"),
                item("tfc_stone_tools:plant_chestplate", title="植物上衣"),
                item("tfc_stone_tools:plant_leggings", title="植物裤"),
                item("tfc_stone_tools:plant_boots", title="植物鞋")],
         rewards=[item("tfc_stone_tools:plant_string", 8), xp(50)])

ch.quest("hunt", 2.5, 8, "第一次狩猎", icon="tfc:large_raw_hide", deps=["javelin"],
         desc=["猎杀动物后，收好掉落的&6尸体&r、肉和兽皮。尸体还能继续分割成肉、骨头、油脂等材料。",
               "",
               "&e适合石器时代的猎物：&r鹿、羊、猪、山羊、野兔、鸡……",
               "&c避开：&r熊、狼、狮子、老虎、鳄鱼、野猪群。在水边也要小心水虎鱼。",
               "",
               "&e技巧：&r",
               "&7- 蹲下靠近，蓄满力再投标枪",
               "&7- &6未腐烂尸体 + 石刀&r可在背包里无序合成，分出肉与副产物；详见「饮水与食物 · 背包分割」",
               "&7- 牛皮、各种颜色的兽皮等模组材料，要先按本节「兽皮刮制」转成&6TFC 生兽皮&r",
               "&7- 生肉很快就会腐烂，&6尽快在篝火上烤熟&r或用盐腌制",
               "",
               "&a刀和原木就能完成第一步刮制。&r完整制革还需要铜器时代的木桶等工具，先存好转出的生兽皮。"],
         tasks=[tag("tfc:raw_hides", title="任意生皮")],
         rewards=[item("firstaid:bandage", 2), xp(40)])

ch.quest("hide_scraping", 2.5, 12.5, "兽皮刮制", icon="butchersdelight:cow_hide", deps=["knife"],
         hide_lines=True, shape="hexagon", size=1.25,
         subtitle="JEI 的刮制配方需要在原木上操作",
         desc=["拿到&6牛皮&r或&6各种颜色的兽皮&r，却不知道 JEI「刮制配方」怎么用？它是在世界里操作的配方。",
               "",
               "&e1.&r 在地上放一块&6原木&r，让它的&6顶面上方保持空气&r",
               "&e2.&r 手持有刮制配方的兽皮，对着&6原木顶面右键&r，把皮铺上去",
               "&e3.&r 换到&6TFC 石刀或金属刀&r，对皮面 &64×4 的 16 个小格&r逐格&6右键&r刮制",
               "&e4.&r 全部格子刮完、皮面改变后，&6打掉铺着的兽皮&r并捡起产物",
               "",
               "&c只反复点同一格不够；不要对着原木侧面放皮。&r刀每刮一格都会损耗耐久。",
               "{@pagebreak}",
               "&6这一步得到什么？&r",
               "&7- &6牛皮&r，以及有对应刮制配方的彩色兽皮 → &6TFC 大型生兽皮&r",
               "&7- &6兔子皮&r → &6TFC 小型生兽皮&r",
               "&7- 屠夫乐事的&6绵羊皮&r另有&6羊皮 + 刀&r的背包合成，得到羊毛和大型生兽皮",
               "",
               "&c「刮制配方」是操作类型，不代表产物一定叫「刮制兽皮」。&r牛皮转换出的仍是&6生兽皮&r，",
               "还需要石灰水浸泡、再次刮制等步骤才能最终做成皮革，完整流程见「铜器时代 · 制革与风箱」。",
               "",
               "&a查配方：&r对手里这张皮按 &eU&r，看用途中的「刮制配方」和输出名称。",
               "没有刮制配方的皮不要硬套这条路线；成品皮革也不需要重新放原木上刮。"],
         tasks=[checkmark("我会在原木顶面逐格刮制兽皮并取回产物")],
         rewards=[item("tfc:wood/log/oak", 4), xp(30)])

ch.quest("bed", 1.25, 10, "茅草床：设置重生点", icon="tfc:thatch_bed", deps=["hunt"],
         shape="hexagon",
         desc=["&6茅草床&r = &62 块茅草&r + &61 张大型生皮&r。",
               "",
               "&c注意：&r茅草床&c只能设置重生点&r，不能睡觉跳过夜晚。",
               "",
               "&a为什么重要：&r本整合包死亡惩罚很重，出门探索前务必设好重生点，"
               "否则你会在世界出生点醒来，离家可能很远。"],
         tasks=[item("tfc:thatch_bed", title="茅草床")],
         rewards=[item("firstaid:plaster", 4), xp(40)])

ch.quest("mob_net", 3.75, 10, "捕捉网", icon="sns:mob_net", deps=["string"], optional=True, shape="diamond",
         desc=["&6捕捉网&r由植物纤维编织而成，可以&e直接抓住&r鸟类和兔子等小动物。",
               "",
               "这是不用追着猎物跑就能获得肉食的好办法。也可以把抓到的动物带回家，为日后的畜牧做准备。"],
         tasks=[item("sns:mob_net", title="捕捉网")],
         rewards=[item("tfc_stone_tools:plant_string", 4), xp(20)])
# ============================================================ D · 泥与窑
ch.quest("clay", 8, 8, "黏土", icon="minecraft:clay_ball", deps=["start"], hide_lines=True,
         desc=["&6黏土&r是陶器的原料，挖掘黏土方块即可获得黏土球（用手或铲子）。",
               "",
               "&e去哪找：&r黏土方块通常在&6河流、湖泊附近&r的地表，颜色比普通泥土更灰、更平滑。"
               "长着&6香蒲、灯芯草&r等特定植物的地方下面往往有黏土。",
               "",
               "&a建议：&r多挖一些！一次陶器制作需要 5 个黏土，第一批你至少要做 6~8 件。"],
         tasks=[item("minecraft:clay_ball", 20, title="黏土 ×20")],
         rewards=[item("minecraft:clay_ball", 16), xp(20)])

ch.quest("knap_clay", 10, 8, "黏土塑形", icon="tfc:ceramic/unfired_vessel", deps=["clay"], shape="hexagon",
         desc=["手持 &65 个以上黏土&r，&e右键&r打开塑形界面，点击方格去掉多余的黏土，按图案捏出想要的形状。",
               "&7（图案可在 JEI 中查看，按 R 查看未烧制陶器的配方）",
               "",
               "&e第一批推荐：&r",
               "&7- &6小缸&r ×2 —— 便携的小储物罐，后期也是熔炼矿石的容器",
               "&7- &6陶锅&r —— 篝火上煮汤、净化水",
               "&7- &6陶碗&r ×2 —— 盛汤、沙拉",
               "&7- &6铸锭模具&r ×2 —— 为铜器时代准备",
               "",
               "&c常见的坑：&r去掉的格子无法恢复，下手前先对照 JEI 里的图案。"],
         tasks=[item("tfc:ceramic/unfired_vessel", title="未烧制的小缸")],
         rewards=[item("minecraft:clay_ball", 16), xp(30)])

ch.quest("kiln", 12, 8, "坑窑", icon="tfc:straw", deps=["knap_clay", "straw"], shape="hexagon",
         size=1.25,
         desc=["&6坑窑&r是石器时代唯一能把黏土烧成陶器的方法。",
               "",
               "&e准备：&r最多 4 件未烧制的陶器、&68 束稻草&r、&68 根原木&r、起火器或火把。",
               "",
               "&e搭建：&r",
               "&e1.&r 挖一个 &61×1 的坑&r，四周和下方必须是实心方块",
               "&e2.&r &e潜行 + 右键&r把陶器放进坑里（最多 4 件）",
               "&e3.&r 手持稻草右键 &68 次&r，铺满盖住陶器",
               "&e4.&r 手持原木右键 &68 次&r，把坑填满",
               "&e5.&r 用起火器点燃（或把燃着的火把丢上去）",
               "{@pagebreak}",
               "坑窑会燃烧约 &68 小时&r（游戏时间），结束后陶器就烧好了。",
               "",
               "&c常见的坑：&r",
               "&7- 坑顶上方必须是&c空气&r，否则不会燃烧",
               "&7- 下雨会浇灭坑窑，建议在屋檐下或晴天搭建",
               "&7- 燃烧中的坑窑是一团真火，&c别站在上面&r"],
         tasks=[checkmark("我已经点燃了一座坑窑")],
         rewards=[item("tfc:straw", 16), item("tfc:wood/log/oak", 16), xp(40)])

ch.quest("finale", 14.5, 8, "陶器时代", icon="tfc:ceramic/vessel", deps=["kiln"], shape="gear", size=1.75,
         subtitle="通往金属之路",
         desc=["&o&7「火与土的结合，是文明的第一件容器。」&r",
               "",
               "烧好的&6小缸&r可以存放 4 格物品，放进去的食物&a腐烂更慢&r。更重要的是：",
               "&6把矿石放进小缸，再放进篝火或坑窑加热，就能熔化成金属液&r —— 这是你的第一次冶炼！",
               "",
               "&a恭喜你走出了石器时代。&r下一步：寻找&6自然铜&r，进入&6铜器时代&r。"],
         tasks=[item("tfc:ceramic/vessel", title="小缸")],
         rewards=[item("tfc:ceramic/vessel"), item("tfc:food/barley_bread", 8), levels(5)])

ch.quest("cookware", 14.5, 10, "陶制厨具", icon="tfc:ceramic/pot", deps=["kiln"], optional=True, shape="diamond",
         desc=["&6陶锅&r放在篝火上可以&6煮汤&r（多种食材，营养更均衡）和&6烧开水&r净化饮用水。",
               "&6陶碗&r用来盛汤和沙拉；&6陶壶&r可以从水源装水随时饮用。",
               "",
               "详细用法见「生存之道 · 饮水与食物」。"],
         tasks=[item("tfc:ceramic/pot", title="陶锅"), item("tfc:ceramic/bowl", title="陶碗"),
                item("tfc:ceramic/jug", title="陶壶")],
         rewards=[item("tfc:food/barley_bread", 4), xp(30)])

ch.quest("molds", 12, 10, "模具与大缸", icon="tfc:ceramic/ingot_mold", deps=["kiln"], optional=True,
         shape="diamond",
         desc=["为接下来的铜器时代做准备：",
               "&7- &6铸锭模具&r：把熔化的金属倒进去得到金属锭",
               "&7- &6工具模具&r（斧、镐、刀……）：直接铸造金属工具头",
               "&7- &6大缸&r：9 格大容量储物，可密封，还能背在身上",
               "",
               "&a建议：&r先多烧几个铸锭模具，它们用多了会碎。"],
         tasks=[item("tfc:ceramic/ingot_mold", 2, title="铸锭模具 ×2"),
                tag("tfc:large_vessels", title="大缸")],
         rewards=[item("minecraft:clay_ball", 24), xp(30)])

ch.section("第一节 · 石与木", ["start", "sticks", "rough_head", "split_heads", "fiber", "string",
                             "knife", "axe", "javelin", "more_tools"])
ch.section("第二节 · 火与居所", ["logs", "support", "firepit", "torch", "drying", "straw", "thatch"])
ch.section("第三节 · 衣与猎", ["plant_clothes", "hunt", "hide_scraping", "bed", "mob_net"])
ch.section("第四节 · 泥与窑", ["clay", "knap_clay", "kiln", "finale", "cookware", "molds"])
